#!/bin/perl

# Project: ptest
# Module:  perl
# Author:  alllex
# Date  :  2014-09-11

use strict;
use perl::tests::test;
use perl::tests::addition;

# -------------------------------------------------------
#                     Benchmark utils
# -------------------------------------------------------

sub benchmark {
    use Benchmark;
    use List::Util qw( min );
    my ($name, $test, $args_getter, $rep, $num) = @_;
    my @params = $args_getter->();

    my @timed = ();

    for my $param (@params) {
        my @results = ();
        for (1..$rep) { 
            my $bm = timeit($num, sub { $test->(@$param); }); 
            push @results, $bm->cpu_a;
        }
        my $best = min(@results);
        push @timed, [$best, $param];
    }

    return ( # Full benchmark info
        $name,
        $rep,
        $num,
        @timed
    );
}

sub now {
    return "" . localtime();
     # use POSIX qw(strftime);
     # my $t = localtime(); strftime "%a %b %e %H:%M:%S %Y", localtime();
     # return $t;
}

sub mk_logname ($) {
    my $test_name = $_[0];
    my $folder = 'results';
    my $lang = perl::tests::test::subject();
    my $ext = 'log';
    return "$folder/$test_name-$lang.$ext";
}

sub tool_name {
    return 'Perl: ' . (split /\n/, `perl -v`)[1];
}

sub log_benchmark ($) {
    my $bench_args = $_[0];
    my ($test_name, $rep, $num, @timed) = benchmark(@$bench_args);
    my $logname = mk_logname($test_name);

    open(my $log, '>', $logname);

    print $log tool_name(), "\n";
    # TODO Organize writing to file
    # print $log "My first report generated by perl\n";

    close $log;

    print "Benchmarked: test($test_name), repeat($rep), number($num):\n";
    for (@timed) { 
        my ($time, $params) = @$_;
        $time = sprintf "%8.5f", $time;
        print "$time // (" . join(", ", @$params) . ")\n";
    }
}

# -------------------------------------------------------
#                   Test compilation
# -------------------------------------------------------

sub tests {

    # makes test bunch from test name
    sub mk_bunch ($$$) { # args(test_name, repeat, number)
        no strict 'refs';
        sub mk_sub { \&{"perl\:\:tests\:\:$_[0]\:\:$_[1]"} }
        return [
            $_[0],                   # test case name
            mk_sub($_[0], 'test'),   # subroutine for test execution
            mk_sub($_[0], 'params'), # subroutine for getting test case params
            $_[1],                   # repeat
            $_[2]                    # number
        ];
    }

    my @prefs = get_prefs();
    my $repeat_fast = $prefs[0];
    my $repeat_mid  = $prefs[1];
    my $repeat_slow = $prefs[2];
    my $number_fast = $prefs[3];
    my $number_mid  = $prefs[4];
    my $number_slow = $prefs[5];

    return (
        mk_bunch("addition", $repeat_fast, $number_fast)
    );
}

# -------------------------------------------------------
#                     Test runner
# -------------------------------------------------------

sub main {
    for (tests()) { log_benchmark($_) }
}

main();